package com.marionete.diegotest;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Customer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;
	private java.lang.Integer money;

	public Customer() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Integer getMoney() {
		return this.money;
	}

	public void setMoney(java.lang.Integer money) {
		this.money = money;
	}

	public Customer(java.lang.String name, java.lang.Integer money) {
		this.name = name;
		this.money = money;
	}

}